// import { cookies } from "next/headers";
// import { createClient } from "@nashural-paid-materials/service-client";

import "../assets/fonts/roboto/style.css";
import "./globals.css";

// const serviceClient = createClient(
//   process.env["SERVICE_URL"]!,
//   process.env["SERVICE_TOKEN"]!,
// );

export const metadata = {
  title: "Наш Урал - Платные материалы",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
